### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by jere-mie** [uwindsorvgdc/website#2]
Rename repository to uwindsorvgdc.github.io so you can move to this as the domain for github pages, as opposed to using the old uwindsor.xyz domain.

**Comment by jere-mie** [comment]
bumping this @chorman0773

**Comment by yasir-saeed** [comment]
I agree

**Comment by jere-mie** [comment]
@chorman0773 👀

**Comment by chorman0773** [comment]
I'll docket it.

**Comment by jere-mie** [comment]
> I'll docket it.

@chorman0773 what does that mean. docket?

**Comment by chorman0773** [comment]
It will be on the agenda.

**Comment by Nafiz1** [comment]
Renamed.
